# Generated by Django 4.1.2 on 2022-10-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_category_listing_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(),
        ),
    ]
